apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: banking 
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: banking
          image: sunitha586/bankingandfinance-sunitha:banking_img
          ports:
          - containerPort: 8081
            
---         
apiVersion: v1
kind: Service
metadata:
  name: banking
spec:
  selector:
    app: banking
  type: NodePort  
  ports:
    - port: 80         
      targetPort: 8081    
      nodePort: 30008  
